// <auto-generated />
using System;
using CitaFacil.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitaFacil.Migrations
{
    [DbContext(typeof(CitaFacilContext))]
    partial class CitaFacilContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitaFacil.Models.Estado", b =>
                {
                    b.Property<int>("Id_Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Estado"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id_Estado");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("CitaFacil.Models.Registrar_Cliente", b =>
                {
                    b.Property<string>("Correo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("int");

                    b.Property<string>("Primer_Apellido")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Primer_Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Segundo_Apellido")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Segundo_Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Telefono_Fijo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("passsword")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("Correo");

                    b.ToTable("Registrar_Cliente");
                });

            modelBuilder.Entity("CitaFacil.Models.Registrar_Negocio", b =>
                {
                    b.Property<string>("Correo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("RolId_Rol")
                        .HasColumnType("int");

                    b.Property<int>("Telefono")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<int>("Telefono_Fijo")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<string>("passsword")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("Correo");

                    b.HasIndex("RolId_Rol");

                    b.ToTable("Registrar_Negocio");
                });

            modelBuilder.Entity("CitaFacil.Models.Roles", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Rol"));

                    b.Property<string>("Nombre_Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Rol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CitaFacil.Models.Registrar_Negocio", b =>
                {
                    b.HasOne("CitaFacil.Models.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId_Rol");

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
